version: "3.8"

services:
  db:
    image: postgres:12.3-alpine
    environment:
      TZ: UTC
      # timesone for postgres
      PGTZ: UTC
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    # Use the host's directory in a container.
    volumes:
      - "./api/tmp/db:/var/lib/postgresql/data"

  api:
    # Specify Dockerfile to use
    build:
      context: ./api
      args:
        WORKDIR: $WORKDIR
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    volumes:
      - "./api:/$WORKDIR"
    # define service dependencies. start db service after starting api service
    depends_on:
      - db
    ports:
      - "$API_PORT:$CONTAINER_PORT"

  front:  
    build:
      context: ./front
      args:
        WORKDIR: $WORKDIR
    command: yarn run dev
    volumes:
      - "./front:/$WORKDIR"
    ports:
      - "$FRONT_PORT:$CONTAINER_PORT"
    depends_on:
      - api
